# -*- coding: utf-8 -*-
"""DAAI_Project03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ytjjIppu0W0j2XTdh4lAvfDDJBNzvYYi
"""

from google.colab import drive
drive.mount("/content/drive")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Mistake_Detection/error_recognition_main

pip install -r requirements.txt

"""**Mistake Detection**

**Split** step, V1, Omnivore
"""

import sys
sys.path.append('/content/drive/MyDrive/Mistake_Detection/error_recognition_main')
!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/.shortcut-targets-by-id/1Ne50XFNHZEsQ3K0_cYI4JdBWqJm3_B7h/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_step_epoch_43.pt --split step --threshold 0.6 --task_name error_recognition

"""**Split** Recordings, V1, Omnivore"""

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_recordings_epoch_33.pt --split recordings --threshold 0.4 --task_name error_recognition

"""**Split** Step, V2, Omnivore"""

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_step_epoch_9.pt --split step --threshold 0.6 --task_name error_recognition

"""**Split** Recordings, V2, Omnivore"""

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_recognition

"""**Split** Step, V1, Slowfast"""

!python -m core.evaluate --variant MLP --backbone slowfast --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/MLP/slowfast/error_recognition_MLP_slowfast_step_epoch_15.pt --split step --threshold 0.6 --task_name error_recognition

"""**Split** Recordings, V1, Slowfast"""

!python -m core.evaluate --variant MLP --backbone slowfast --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/MLP/slowfast/error_recognition_MLP_slowfast_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_recognition

"""**Split** Step, V2, Slowfast"""

!python -m core.evaluate --variant Transformer --backbone slowfast --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/Transformer/slowfast/error_recognition_Transformer_slowfast_step_epoch_25.pt --split step --threshold 0.6 --task_name error_recognition

"""**Split** Recordings, V2, Slowfast"""

!python -m core.evaluate --variant Transformer --backbone slowfast --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/Transformer/slowfast/error_recognition_Transformer_slowfast_recordings_epoch_49.pt --split recordings --threshold 0.4 --task_name error_recognition

"""**Error Category Recognition**

**Split** step, V1, Omnivore, Preparation Error
"""

import sys
sys.path.append('/content/drive/MyDrive/Mistake_Detection/error_recognition_main')
!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/.shortcut-targets-by-id/1Ne50XFNHZEsQ3K0_cYI4JdBWqJm3_B7h/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_step_epoch_43.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category "Preparation Error"

"""**Split** Recordings, V1, Omnivore, Preparation Error"""

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_recordings_epoch_33.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category "Preparation Error"

"""**Split** Step, V2, Omnivore, Preparation Error"""

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_step_epoch_9.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category "Preparation Error"

"""**Split** Recordings, V2, Omnivore, Preparation Error"""

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category "Preparation Error"

"""**Split** step, V1, Omnivore, Temperature Error"""

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/.shortcut-targets-by-id/1Ne50XFNHZEsQ3K0_cYI4JdBWqJm3_B7h/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_step_epoch_43.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category "Temperature Error"

"""**Split** recordings, V1, Omnivore, Temperature Error"""

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_recordings_epoch_33.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category "Temperature Error"

"""**Split** Step, V2, Omnivore, Temperature Error"""

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_step_epoch_9.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category "Temperature Error"

"""**Split** Recordings, V2, Omnivore, Temperature Error"""

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category "Temperature Error"

"""**Split** step, V1, Omnivore, Measurement Error"""

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/.shortcut-targets-by-id/1Ne50XFNHZEsQ3K0_cYI4JdBWqJm3_B7h/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_step_epoch_43.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category "Measurement Error"

"""**Split** recordings, V1, Omnivore, Measurement Error"""

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_recordings_epoch_33.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category "Measurement Error"

"""**Split** Step, V2, Omnivore, Measurement Error"""

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_step_epoch_9.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category "Measurement Error"

"""**Split** Recordings, V2, Omnivore, Measurement Error"""

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category "Measurement Error"

"""**Split** Step, V1, Omnivore, Timing Error"""

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/.shortcut-targets-by-id/1Ne50XFNHZEsQ3K0_cYI4JdBWqJm3_B7h/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_step_epoch_43.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category "Timing Error"

"""**Split** Recordings, V1, Omnivore, Timing Error"""

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_recordings_epoch_33.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category "Timing Error"

"""**Split** Step, V2, Omnivore, Timing Error"""

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_step_epoch_9.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category "Timing Error"

"""**Split** Recordings, V2, Omnivore, Timing Error"""

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category "Timing Error"

"""**Split** step, V1, Omnivore, Technique Error"""

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/.shortcut-targets-by-id/1Ne50XFNHZEsQ3K0_cYI4JdBWqJm3_B7h/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_step_epoch_43.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category "Technique Error"

"""**Split** recordings, V1, Omnivore, Technique Error"""

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_recordings_epoch_33.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category "Technique Error"

"""**Split** Step, V2, Omnivore, Technique Error"""

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_step_epoch_9.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category "Technique Error"

"""**Split** Recordings, V2, Omnivore, Technique Error"""

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category "Technique Error"

"""**Train model LSTM**

Omnivore
"""

import sys
sys.path.append('/content/drive/MyDrive/Mistake_Detection/error_recognition_main')
!python /content/drive/MyDrive/Mistake_Detection/error_recognition_main/train_er.py --variant LSTM --backbone omnivore --split step --task_name error_recognition --num_epochs 50 --batch_size 512 --test-batch-size 512

import sys
sys.path.append('/content/drive/MyDrive/Mistake_Detection/error_recognition_main')
!python /content/drive/MyDrive/Mistake_Detection/error_recognition_main/train_er.py --variant LSTM --backbone omnivore --split recordings --task_name error_recognition --num_epochs 50 --batch_size 512 --test-batch-size 512

"""Slowfast"""

import sys
sys.path.append('/content/drive/MyDrive/Mistake_Detection/error_recognition_main')
!python /content/drive/MyDrive/Mistake_Detection/error_recognition_main/train_er.py --variant LSTM --backbone slowfast --split step --task_name error_recognition --num_epochs 50 --batch_size 512 --test-batch-size 512

import sys
sys.path.append('/content/drive/MyDrive/Mistake_Detection/error_recognition_main')
!python /content/drive/MyDrive/Mistake_Detection/error_recognition_main/train_er.py --variant LSTM --backbone slowfast --split recordings --task_name error_recognition --num_epochs 50 --batch_size 512 --test-batch-size 512

"""**Mistake detection**

Omnivore
"""

!python -m core.evaluate --variant LSTM --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/LSTM/omnivore/error_recognition_step_omnivore_LSTM_video_best.pt --split step --threshold 0.6 --task_name error_recognition

!python -m core.evaluate --variant LSTM --backbone omnivore --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/LSTM/omnivore/error_recognition_recordings_omnivore_LSTM_video_best.pt --split recordings --threshold 0.4 --task_name error_recognition

"""Slowfast"""

!python -m core.evaluate --variant LSTM --backbone slowfast --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/LSTM/slowfast/error_recognition_step_slowfast_LSTM_video_best.pt --split step --threshold 0.6 --task_name error_recognition

!python -m core.evaluate --variant LSTM --backbone slowfast --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/LSTM/slowfast/error_recognition_recordings_slowfast_LSTM_video_best.pt --split recordings --threshold 0.4 --task_name error_recognition

"""**FEATURE EXTRACTOR Perception Encoder**"""

pip install git+https://github.com/facebookresearch/pytorchvideo.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Mistake_Detection
import sys
sys.path.append('/content/drive/MyDrive/Mistake_Detection/perception_models_main')
!python -m feature_extractors_main.segment_features.segment_feature_extractor --backbone perception_encoder

"""**Train Model - Point 3**"""

import sys
sys.path.append('/content/drive/MyDrive/Mistake_Detection/error_recognition_main')
!python /content/drive/MyDrive/Mistake_Detection/error_recognition_main/train_er.py --variant MLP --backbone perception_encoder --split step --task_name error_recognition --num_epochs 50 --batch_size 512 --test-batch-size 512

import sys
sys.path.append('/content/drive/MyDrive/Mistake_Detection/error_recognition_main')
!python /content/drive/MyDrive/Mistake_Detection/error_recognition_main/train_er.py --variant MLP --backbone perception_encoder --split recordings --task_name error_recognition --num_epochs 50 --batch_size 512 --test-batch-size 512

import sys
sys.path.append('/content/drive/MyDrive/Mistake_Detection/error_recognition_main')
!python /content/drive/MyDrive/Mistake_Detection/error_recognition_main/train_er.py --variant Transformer --backbone perception_encoder --split step --task_name error_recognition --num_epochs 50 --batch_size 512 --test-batch-size 512

import sys
sys.path.append('/content/drive/MyDrive/Mistake_Detection/error_recognition_main')
!python /content/drive/MyDrive/Mistake_Detection/error_recognition_main/train_er.py --variant LSTM --backbone perception_encoder --split step --task_name error_recognition --num_epochs 50 --batch_size 32 --test-batch-size 32

import sys
sys.path.append('/content/drive/MyDrive/Mistake_Detection/error_recognition_main')
!python /content/drive/MyDrive/Mistake_Detection/error_recognition_main/train_er.py --variant LSTM --backbone perception_encoder --split recordings --task_name error_recognition --num_epochs 50 --batch_size 32 --test-batch-size 32

"""**Mistake Detection - Point 3**"""

!python -m core.evaluate --variant MLP --backbone perception_encoder --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/MLP/perception_encoder/error_recognition_step_perception_encoder_MLP_video_best.pt --split step --threshold 0.6 --task_name error_recognition

!python -m core.evaluate --variant MLP --backbone perception_encoder --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/MLP/perception_encoder/error_recognition_recordings_perception_encoder_MLP_video_best.pt --split recordings --threshold 0.4 --task_name error_recognition

!python -m core.evaluate --variant Transformer --backbone perception_encoder --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/Transformer/perception_encoder/error_recognition_step_perception_encoder_Transformer_video_best.pt --split step --threshold 0.6 --task_name error_recognition

!python -m core.evaluate --variant LSTM --backbone perception_encoder --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/LSTM/perception_encoder/error_recognition_step_perception_encoder_LSTM_video_best.pt --split step --threshold 0.6 --task_name error_recognition

!python -m core.evaluate --variant LSTM --backbone perception_encoder --ckpt /content/drive/MyDrive/Mistake_Detection/error_recognition_main/checkpoints/error_recognition_best/LSTM/perception_encoder/error_recognition_recordings_perception_encoder_LSTM_video_best.pt --split recordings --threshold 0.4 --task_name error_recognition